const ExcelJS = require('exceljs');
const path = require('path');
const fs = require('fs');

// Import schemas from reportSchemas
const { REPORT_SCHEMAS } = require('../utils/reportSchemas.cjs');

const OUTPUT_DIR = path.join(__dirname, '../templates/defaults');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

/**
 * Create a default Excel template for a given module
 */
async function createDefaultTemplate(moduleName, columns) {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Report');

    // --- HEADER SECTION (Rows 1-8) ---
    // Row 1: Company Logo / Branding Area
    worksheet.mergeCells('A1:E1');
    const titleCell = worksheet.getCell('A1');
    titleCell.value = 'CafeFlow POS System';
    titleCell.font = { size: 20, bold: true, color: { argb: 'FF4F46E5' } };
    titleCell.alignment = { vertical: 'middle', horizontal: 'center' };
    worksheet.getRow(1).height = 30;

    // Row 2: Report Title
    worksheet.mergeCells('A2:E2');
    const reportTitle = worksheet.getCell('A2');
    reportTitle.value = `{{Module_Name}} Report`;
    reportTitle.font = { size: 16, bold: true };
    reportTitle.alignment = { vertical: 'middle', horizontal: 'center' };
    worksheet.getRow(2).height = 25;

    // Row 3: Empty spacing
    worksheet.getRow(3).height = 5;

    // Row 4-6: Metadata
    worksheet.getCell('A4').value = 'Generated Date:';
    worksheet.getCell('B4').value = '{{Generated_Date}}';
    worksheet.getCell('A4').font = { bold: true };

    worksheet.getCell('A5').value = 'Generated Time:';
    worksheet.getCell('B5').value = '{{Generated_Time}}';
    worksheet.getCell('A5').font = { bold: true };

    worksheet.getCell('A6').value = 'Generated By:';
    worksheet.getCell('B6').value = '{{Generated_By}}';
    worksheet.getCell('A6').font = { bold: true };

    // Row 7: Empty spacing
    worksheet.getRow(7).height = 5;

    // Row 8: Column Headers (Visual Labels for Users)
    columns.forEach((col, idx) => {
        const cell = worksheet.getCell(8, idx + 1);
        cell.value = col;
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FF4F46E5' }
        };
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
        cell.border = {
            top: { style: 'thin' },
            left: { style: 'thin' },
            bottom: { style: 'thin' },
            right: { style: 'thin' }
        };
    });
    worksheet.getRow(8).height = 25;

    // Row 9: Template Mapping Row (with {{placeholders}})
    // This is where the system reads column mappings
    columns.forEach((col, idx) => {
        const cell = worksheet.getCell(9, idx + 1);
        cell.value = `{{${col}}}`;
        cell.font = { italic: true, color: { argb: 'FF94A3B8' }, size: 9 };
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
    });
    worksheet.getRow(9).height = 18;

    // Set column widths
    worksheet.columns = columns.map(col => ({
        width: Math.max(15, col.length + 5)
    }));

    // Add some styling to metadata section
    ['A4', 'A5', 'A6'].forEach(addr => {
        worksheet.getCell(addr).fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFF1F5F9' }
        };
    });

    // Save the file
    const filename = path.join(OUTPUT_DIR, `${moduleName}.xlsx`);
    await workbook.xlsx.writeFile(filename);
    console.log(`✓ Created: ${moduleName}.xlsx`);
}

/**
 * Generate all default templates
 */
async function generateAllTemplates() {
    console.log('Generating default Excel templates...\n');

    for (const [moduleName, columns] of Object.entries(REPORT_SCHEMAS)) {
        try {
            await createDefaultTemplate(moduleName, columns);
        } catch (error) {
            console.error(`✗ Failed to create ${moduleName}:`, error.message);
        }
    }

    console.log(`\n✓ All templates generated in: ${OUTPUT_DIR}`);
}

// Run the generator
generateAllTemplates().catch(err => {
    console.error('Fatal error:', err);
    process.exit(1);
});
